---
# tasks file for
- name: Wait for port to be available
  become: false
  block:
    - name: Constitute minimal facts
      ansible.builtin.wait_for_connection:
        timeout: "{{ bootstrap_timeout }}"
      vars:
        ansible_connection: ssh
  rescue:
    - name: Constitute minimal facts
      ansible.builtin.include_tasks:
        file: gather_facts.yml

    - name: Install bootstrap packages (raw)
      ansible.builtin.raw: "{{ bootstrap_install.raw }}"
      register: bootstrap_install_packages
      become: true
      changed_when:
        - (bootstrap_install.stdout_regex in bootstrap_install_packages.stdout and
          bootstrap_os_family in [ "Alpine", "Archlinux", "Gentoo" ]) or
          (bootstrap_install.stdout_regex not in bootstrap_install_packages.stdout and
          bootstrap_os_family in [ "Debian", "RedHat", "Rocky", "Suse" ])

- name: Ensure system is prepared
  become: false
  block:
    - name: Gather ansible facts
      ansible.builtin.setup:
    - name: Update cache
      ansible.builtin.include_tasks:
        file: update_cache.yml
    - name: Install bootstrap packages (package)
      become: true
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ bootstrap_facts_packages.split() }}"
